feature zchainbchn 77
evenlab/gosdk pull request #13
Opened 2021-11-02 14:23 UTC by jkrus

Created proto files for token_pool, token_pool_req. Implemented pb files into wrappers. Created (refactoring) unit test for them.

2021-11-02 15:24 UTC, MurashovVen requested changes

2021-11-02 15:24 UTC, MurashovVen commented on zmagmacore/magmasc/pb/proto/token_pool_req.proto
> +  string payee_id = 2;  // @gotags: json:"payee_id"
**json** тэги генерируются автоматически с опцией **omitempty**, так что, думаю, можно избавится от дублирования тэгов в той части, где они могут быть пустыми.

2021-11-02 15:24 UTC, MurashovVen commented on zmagmacore/magmasc/pb/access_point.pb.go
>  	0x74, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x05, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01,
Нужно перегенерировать все _**pb.go**_ файлы.

2021-11-02 15:24 UTC, MurashovVen commented on zmagmacore/magmasc/token_pool_req.go
> +	switch { // is invalid
Можно упростить до 1 блока **if**

2021-11-02 15:33 UTC, jkrus commented on zmagmacore/magmasc/pb/proto/token_pool_req.proto
> +  string payee_id = 2;  // @gotags: json:"payee_id"
Ок. Я просто скопировал структуру json из оригинала. Таким образом получается, что json тег нужно удалить только у id. Верно?

2021-11-02 15:34 UTC, jkrus commented on zmagmacore/magmasc/pb/access_point.pb.go
>  	0x74, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x05, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01,
Они свежесгененрированные. make generate-proto был выполнен. Иначе как бы я получил новые pb-шки.

2021-11-03 07:17 UTC, MurashovVen approved these changes

2021-11-03 08:14 UTC, MurashovVen approved these changes

2021-11-03 09:17 UTC, closed without merging