feature ZCHAINBCHN-30
evenlab/gosdk pull request #3
Opened 2021-09-16 07:52 UTC by jkrus

2021-09-16 13:04 UTC, MurashovVen requested changes

2021-09-16 13:12 UTC, jkrus commented on zmagmacore/config/access_point.go
> +		minStake      bool
done

2021-09-16 13:13 UTC, jkrus commented on zmagmacore/magmasc/terms.go
>  		AccessPointID   string         `json:"apid"`                        // access point id
done

2021-09-16 13:14 UTC, jkrus commented on zmagmacore/magmasc/api.go
> +func AccessPointMinStakeFetch(ID string) (int64, error) {
done

2021-09-17 08:46 UTC, MurashovVen commented on zmagmacore/magmasc/access_point.go
> +	ProviderExtID string `yaml:"provider_ext_id"`
Нужно заменить тег `yaml` на `json`

2021-09-17 11:29 UTC, MurashovVen approved these changes

2021-09-20 14:26 UTC, closed without merging